name: cutting_height
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.3.1
  - r-tidyverse=2.0.0
  - r-rstatix=0.7.2
  - r-nlme=3.1_162
  - r-emmeans=1.8.7
  - r-ggpubr=0.6.0
  - snakemake=7.30.2